translations: {
    pt: {
        "RedAlert's Scripts Pack": "Pacote de Scripts RedAlert",
        Help: 'Ajuda',
        'There was an error!': 'Ocorreu um erro!',
        'There are no scripts!': 'Não há scripts!',
        'There has been an error fetching the scripts!': 'Ocorreu um erro ao buscar os scripts!',
        'scripts listed': 'scripts listados',
        'Script Name': 'Nome do Script',
        'Script Loader': 'Carregador de Script',
        Forum: 'Fórum',
        Demo: 'Demonstração',
        New: 'Novo',
        'Search scripts ...': 'Pesquisar scripts ...',
        'Fetching scripts ...': 'Buscando scripts ...',
        'Script is not allowed to be used on this TW market!': 'O script não pode ser usado neste mercado do TW!',
        NEW: 'NOVO',
        ALL: 'TODOS',
        Add: 'Adicionar',
        'Quick-bar item has been added!': 'Item adicionado à barra rápida!',
        'Go to forum': 'Ir para o fórum',
        'View demo video': 'Ver vídeo de demonstração',
        'Add script on Quick-bar': 'Adicionar script na barra rápida',
        'This script has no demo video!': 'Este script não possui vídeo de demonstração!',
    },
}
